[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[features]
nightly = []

[dependencies]
chrono = "0.4.42"
clap = { version = "4.5.53", features = ["derive"] }
dotenv = "0.15.0"
reqwest = { version = "0.12.24", features = ["blocking"] }

[build-dependencies]
rustc_version = "0.4.1"
